# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Desenvolvimneto', 'Desenvolvimento'), ('Modelagem', 'Modelagem'), ('Engenharia de Requisitos', 'Engenharia de Requisitos'), ('Omologação', 'Omologação'), ('Testes', 'Testes')], max_length=100)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_criacao',),
            },
        ),
    ]
