# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Desenvolvimneto', 'Desenvolvimento'), ('Modelagem', 'Modelagem'), ('Engenharia de Requisitos', 'Engenharia de Requisitos'), ('Omologação', 'Omologação'), ('Testes', 'Testes')], max_length=100)),
            ],
            options={
                'ordering': ('data_criacao',),
            },
        ),
    ]
